name: "SMZDM Check-in Bot"

on:
  workflow_dispatch:

  # 取消下面两行注释，务必自行更改为随机时间
   schedule:
     - cron: "30 1 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Working
        env:
          SMZDM_COOKIE: ${{ secrets.__jsluid_h=3fe6b2aa627954c1308fefe5ffbb0de5; __ckguid=bY15nf7Ypru2Tsa27FGbYAr7; device_id=213070643316629774552261575288c941a1eff248149a2049f82793f1; homepage_sug=d; r_sort_type=score; __jsluid_s=fe6434085af5cdc4e86f560828bd8722; smzdm_user_source=58310B38FAEC40420AEEE8603D27BF1C; footer_floating_layer=0; sess=BA-g9Aox8SQ5Fj2lRItq5kbKGVbn7WtYoP5v6FO2TEo74nF8HjfDVxf9y7oGZE%2Fc6qS3IPoO2RSqceP6HP%2Bedo0KGDeIKUGvbOYv97%2BiFtiPnsefhCDUDHXq2kQ; user=user%3A2743736440%7C2743736440; smzdm_id=2743736440; smzdm_user_view=B0F7E4AEDBA5B6CB3E8BF8D2863C5362; ss_ab=ss35; ssmx_ab=mxss46; s_his=%E5%85%AB%E9%A9%AC%E8%8C%B6%E4%B8%9A%2C%E5%B0%8F%E7%B1%B3%E7%94%B5%E5%8A%A8%E8%9E%BA%E4%B8%9D%E5%88%80%2C%E8%A1%80%E7%B3%96%E4%BB%AA%2C%E8%A1%80%E7%B3%96%E4%BB%AA%20%E5%BC%BA%E7%94%9F%2C%E8%A1%80%E7%B3%96%E4%BB%AA%20%E6%AC%A7%E5%A7%86%E9%BE%99%2C%E8%9E%BA%E4%B8%9D%E5%88%80%2C%E5%8D%9A%E4%B8%96; _zdmA.vid=*; ad_date=24; bannerCounter=%5B%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%5D; ad_json_feed=%7B%7D; _zdmA.uid=ZDMA.VkPolbavm.1674533217.2419200; _zdmA.time=1674533217296.0.https%3A%2F%2Fwww.smzdm.com%2F }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          SC_KEY: ${{ secrets.SC_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: python main.py
